apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  completions: 9
  parallelism: 9
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: playwright
          image: nageshkumardoc/playwright-testing:latest
          command: ["sh", "-c", "npx playwright test --shard=$((JOB_COMPLETION_INDEX + 1))/9"]
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
            - name: USERNAME
              value: "Admin"
            - name: PASSWORD
              value: "admin123"
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          volumeMounts:
            - name: report
              mountPath: /app/playwright-report
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Never
      volumes:
        - name: report
          name: report
          hostPath:
            path: /tmp/playwright-report
            type: DirectoryOrCreate
  backoffLimit: 0