apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: playwright
          image: pw-test:latest
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running Playwright tests...";
              npx playwright test;

              echo "Copying report to shared volume...";
              mkdir -p /shared;
              cp -r playwright-report/* /shared/ || echo "No report found";

          volumeMounts:
            - name: report-volume
              mountPath: /shared

          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: playwright-secret
                  key: base_url
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: playwright-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playwright-secret
                  key: password

      volumes:
        - name: report-volume
          hostPath:
            path: /tmp/playwright-report
            type: DirectoryOrCreate